//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Properties.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar.
        /// </summary>
        internal static string Able {
            get {
                return ResourceManager.GetString("Able", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        internal static string Actual_password {
            get {
                return ResourceManager.GetString("Actual password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos agregados.
        /// </summary>
        internal static string Added_permits {
            get {
                return ResourceManager.GetString("Added permits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Profile.
        /// </summary>
        internal static string Asignar_Perfil {
            get {
                return ResourceManager.GetString("Asignar Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set profiles.
        /// </summary>
        internal static string Asignar_Perfiles {
            get {
                return ResourceManager.GetString("Asignar Perfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobro.
        /// </summary>
        internal static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Cambiar_Contrseña {
            get {
                return ResourceManager.GetString("Cambiar Contrseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string Cambiar_Idioma {
            get {
                return ResourceManager.GetString("Cambiar Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (mins).
        /// </summary>
        internal static string Cant_tiempo__mins_ {
            get {
                return ResourceManager.GetString("Cant tiempo (mins)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro de tarjeta.
        /// </summary>
        internal static string Card_number {
            get {
                return ResourceManager.GetString("Card number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Cerrar_sesion {
            get {
                return ResourceManager.GetString("Cerrar sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Idioma.
        /// </summary>
        internal static string Change_language {
            get {
                return ResourceManager.GetString("Change language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contrseña.
        /// </summary>
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar permisos.
        /// </summary>
        internal static string Clear_permits {
            get {
                return ResourceManager.GetString("Clear permits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Cobro {
            get {
                return ResourceManager.GetString("Cobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        internal static string Cod_seguridad {
            get {
                return ResourceManager.GetString("Cod seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectuar cobro.
        /// </summary>
        internal static string Confirm_payment {
            get {
                return ResourceManager.GetString("Confirm payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual password.
        /// </summary>
        internal static string Contraseña_actual {
            get {
                return ResourceManager.GetString("Contraseña actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Contraseña_nueva {
            get {
                return ResourceManager.GetString("Contraseña nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Profile.
        /// </summary>
        internal static string Crear_Perfil {
            get {
                return ResourceManager.GetString("Crear Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profiles.
        /// </summary>
        internal static string Crear_Perfiles {
            get {
                return ResourceManager.GetString("Crear Perfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Perfil.
        /// </summary>
        internal static string Create_Profile {
            get {
                return ResourceManager.GetString("Create Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Perfiles.
        /// </summary>
        internal static string Create_profiles {
            get {
                return ResourceManager.GetString("Create profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desable.
        /// </summary>
        internal static string Deshabilitar {
            get {
                return ResourceManager.GetString("Deshabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm payment.
        /// </summary>
        internal static string Efectuar_cobro {
            get {
                return ResourceManager.GetString("Efectuar cobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear permits.
        /// </summary>
        internal static string Eliminar_permisos {
            get {
                return ResourceManager.GetString("Eliminar permisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string Estacion {
            get {
                return ResourceManager.GetString("Estacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento.
        /// </summary>
        internal static string Expiration_date {
            get {
                return ResourceManager.GetString("Expiration date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental management.
        /// </summary>
        internal static string Gestion_de_alquileres {
            get {
                return ResourceManager.GetString("Gestion de alquileres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Able.
        /// </summary>
        internal static string Habilitar {
            get {
                return ResourceManager.GetString("Habilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Iniciar_sesion {
            get {
                return ResourceManager.GetString("Iniciar sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesion.
        /// </summary>
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesion.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        internal static string Metodo_de_pago {
            get {
                return ResourceManager.GetString("Metodo de pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify users.
        /// </summary>
        internal static string Modificar_usuarios {
            get {
                return ResourceManager.GetString("Modificar usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar usuarios.
        /// </summary>
        internal static string Modify_users {
            get {
                return ResourceManager.GetString("Modify users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Monto {
            get {
                return ResourceManager.GetString("Monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña nueva.
        /// </summary>
        internal static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner´s name.
        /// </summary>
        internal static string Nombre_del_titular {
            get {
                return ResourceManager.GetString("Nombre del titular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string Nro_de_tarjeta {
            get {
                return ResourceManager.GetString("Nro de tarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del titular.
        /// </summary>
        internal static string Owner_s_name {
            get {
                return ResourceManager.GetString("Owner\'s name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo de pago.
        /// </summary>
        internal static string Payment_method {
            get {
                return ResourceManager.GetString("Payment method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permits.
        /// </summary>
        internal static string Permisos {
            get {
                return ResourceManager.GetString("Permisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added permits.
        /// </summary>
        internal static string Permisos_agregados {
            get {
                return ResourceManager.GetString("Permisos agregados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos.
        /// </summary>
        internal static string Permits {
            get {
                return ResourceManager.GetString("Permits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Cuenta.
        /// </summary>
        internal static string Register_account {
            get {
                return ResourceManager.GetString("Register account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register account.
        /// </summary>
        internal static string Registrar_Cuenta {
            get {
                return ResourceManager.GetString("Registrar Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de alquileres.
        /// </summary>
        internal static string Rental_management {
            get {
                return ResourceManager.GetString("Rental management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod seguridad.
        /// </summary>
        internal static string Security_code {
            get {
                return ResourceManager.GetString("Security code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Perfil.
        /// </summary>
        internal static string Set_Profile {
            get {
                return ResourceManager.GetString("Set Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Perfiles.
        /// </summary>
        internal static string Set_profiles {
            get {
                return ResourceManager.GetString("Set profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacion.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant tiempo (mins).
        /// </summary>
        internal static string Time__mins_ {
            get {
                return ResourceManager.GetString("Time (mins)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        internal static string User_ {
            get {
                return ResourceManager.GetString("User:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string Usuario_ {
            get {
                return ResourceManager.GetString("Usuario:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string Vencimiento {
            get {
                return ResourceManager.GetString("Vencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
